### ISSUE TITLE
Dockerfile update

### ISSUE THREAD

**Issue by dasturge** [DCAN-Labs/abcd-hcp-pipeline#13]
artful aardvark is no longer supported, so we probably want to swap over to the newer Ubuntu 18.04 LTS.

Here are some of the changes we needed to make to base libraries to handle everything:
- install perl 5.20.3
- install libnetcf
- fix libz so
- fix libstdc++6 so

perl has to do with freesurfer issues, but I don't recall where the other libraries were causing hiccups.

**Comment by madisoth** [comment]
Resolved by https://github.com/DCAN-Labs/abcd-hcp-pipeline/pull/21
