### ISSUE TITLE
bug: BIDS App expects AcquisitionMatrixPE metadata in get_realdwelltime function, even in the absence of fieldmaps

### ISSUE THREAD

**Issue by uriartel** [DCAN-Labs/abcd-hcp-pipeline#17]
A bug was found that is preventing the BIDS app to run on the ABIDE dataset. The information in the json files for the ABIDE data is different than that of the ABCD dataset. The ABIDE json files are organized using "AcquisitionMatrix" where as the ABCD json files uses "AcquisitionMatrixPE". 

Example for ABIDE
"AcquisitionMatrix": "80x64",

Example for ABCD 
"AcquisitionMatrixPE": 90,

Due to this difference the BIDS app can not be run on the ABIDE dataset. The ABIDE json files may need to be converted, or the script can be adjusted in order to compensate the difference of the json files.

**Comment by ericearl** [comment]
@uriartel Can you please paste just the Python traceback from your error log that had the relevant lines in helpers.py, etc.?

**Comment by dasturge** [comment]
There are two fixes for this.  Firstly, we can change the logic in the ParameterSettings class to only check for this metadata in the presence of FieldMaps.  The second, is to write flexible logic to read the nPE steps from either of these json fields.  We should do both.

**Comment by uriartel** [comment]
/home/exacloud/lustre1/fnl_lab/data/HCP/logs/ABIDE_BIDS/BIDS_ABIDEI/NYU/sub-0050952 

here is the path to the .err and .out files. 

Traceback (most recent call last):
  File "/app/run.py", line 364, in <module>
    _cli()
  File "/app/run.py", line 67, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 263, in interface
    session_spec = ParameterSettings(session, out_dir)
  File "/app/pipelines.py", line 106, in __init__
    self.bids_data['t1w_metadata'])
  File "/app/helpers.py", line 196, in get_realdwelltime
    num_steps = metadata['AcquisitionMatrixPE']
KeyError: 'AcquisitionMatrixPE'

I believe that these are the relevant lines.

**Comment by LuciMoore** [comment]
It appears that the issue might have been addressed implicitly through subsequent updates, changes, or improvements. Since there hasn't been any recent activity or confirmation regarding its relevance, we are considering this issue resolved.

If you believe the matter is still relevant or requires further attention, please feel free to reopen the issue, and we'll be more than happy to revisit and address it promptly.
