### ISSUE TITLE
DCANBOLD processing display task-res instead of task-rest in output folder 

### ISSUE THREAD

**Issue by uriartel** [DCAN-Labs/abcd-hcp-pipeline#19]
I ran the ABIDE BIDS data through the BIDS app and noticed errors in the functional data. 

Concatenating task-rest1 to `../../ses-None/files/MNINonLinear/Results/task-res_DCANBOLDProc_v4.0.0_Atlas.dtseries.nii`

```
BIDS_ABIDEI/NYU/sub-*/func/
├── sub-*_task-rest_bold.json
└── sub-*_task-rest_run-1_bold.nii.gz
```

**Comment by ericearl** [comment]
Thanks @uriartel!  We are inspecting this issue now and think it may be related to the expectation on BIDS input data to have been converted by Dcm2Bids and have the run numbers labeled as two-digit numbers.  Either way, this is a problem and we need to find a good solution.

**Comment by madisoth** [comment]
PR #39 updates the handling of session/task labels and run indices by both helpers.py and dcan_bold_processing, which is likely to resolve this issue.
