### ISSUE TITLE
Include Dockerfile generator script for neurodocker in repo

### ISSUE THREAD

**Issue by DavidEWarrenPhD** [DCAN-Labs/abcd-hcp-pipeline#23]
The included Dockerfile appears to be generated using neurodocker, but a script containing the neurodocker call is not included in this repo.  Including the neurodocker generator script would be convenient and would enhance reproducibility.  Example at https://github.com/kaczmarj/neurodocker/blob/master/examples/conda_python/generate.sh.

**Comment by ericearl** [comment]
@DavidEWarrenPhD Thanks for pointing this out!  We should remove most of that from the Dockerfile and credit kaczmarj for what came from their neurodocker.  What happened was we used kaczmarj's neurodocker from DockerHub for the original first base Dockerfile build and just never deleted all the comments after we had basically rewiritten the whole Dockerfile.  Regardless, I will leave this issue open until we make those corrections.
