### ISSUE TITLE
Access rights from Docker output

### ISSUE THREAD

**Issue by MartinBa9210** [DCAN-Labs/abcd-hcp-pipeline#25]
Thanks for providing this great pipeline, works fine for me!

One comment, as it drives me nuts the first time, is accessing the Docker output on Linux machines. It turned out, that within Docker it run as root, but you might not be root any longer when you access your data.

To be sure about the correct rights put the flag --user "$(id -u):$(id -g)" to the docker options

so its:

docker run --rm --user "$(id -u):$(id -g)" \
    -v /path/to/bids_dataset:/bids_input:ro \
    -v /path/to/outputs:/output \
    -v /path/to/freesurfer/license:/license \
    dcanlabs/nhp-abcd-bids-pipeline /bids_input /output
    --freesurfer-license=/license [OPTIONS]

as a minimal command example.

Best,
Martin

**Comment by ericearl** [comment]
This is a great observation, @MartinBa9210 , thanks!  I will include this in the next revision.
