### ISSUE TITLE
Error in Processing

### ISSUE THREAD

**Issue by tundejunaid** [DCAN-Labs/abcd-hcp-pipeline#28]
The error i got while processing my data is in BIDS format @ericearl 
Traceback (most recent call last):
  File "/app/run.py", line 364, in <module>
    _cli()
  File "/app/run.py", line 67, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 263, in interface
    session_spec = ParameterSettings(session, out_dir)
  File "/app/pipelines.py", line 106, in __init__
    self.bids_data['t1w_metadata'])
  File "/app/helpers.py", line 195, in get_realdwelltime
    pBW = metadata['PixelBandwidth']
KeyError: 'PixelBandwidth'
This is the error message i got, I think i can understand that there could be an issue with my input(session not properly assigned in the BIDS data format, but it is the pBW or pixel Bandwidth error i am unable to know or fix. any help or suggestion would be appreciated.

**Comment by ericearl** [comment]
@tundejunaid Is there a `"PixelBandwidth"` field in your BIDS sidecar JSON for your T1 data?  Also, what do you mean by "session not properly assigned in the BIDS data format"?  Also, what scanner manufacturer is this data from?  I hope I can help.

**Comment by tundejunaid** [comment]
I found out there was none and there are some other parameters not found like InPlanePhaseDirection and ParallelReductionPlane. And they seem really important for the structural analysis. I am using A Philipps scanner and I have no field map image. I am using this for my master thesis and any help or information would be appreciated.

**Comment by ericearl** [comment]
@tundejunaid I would talk to whoever is closest to the MRI acquisition data and ask them for whatever the Philips equivalent of a Siemens "protocol PDF" is for acquisition timing parameters and the like.  You will likely need a few of those fields inserted into your BIDS sidecar JSONs for processing.  If you determine these fields unnecessary for your processing needs, then we can consider making a change to this application to accommodate unnecessary fields.

You may also want to consider satisfying the official BIDS validator for pristine input data before trying to process.
https://github.com/bids-standard/bids-validator#quickstart

**Comment by tundejunaid** [comment]
All is working fine, I think the problem was the first dataset I tried it with. the conversion to BIDS was not from the DICOM but from a REC File. When I tried with another Data converted From DICOM it was all good
