### ISSUE TITLE
provide an option to run filemapper at the end

### ISSUE THREAD

**Issue by ericfeczko** [DCAN-Labs/abcd-hcp-pipeline#29]
It would be great if the pipeline could include an option to run filemapper after it finishes. Not sure how feasible that would be to pull off.

**Comment by ericearl** [comment]
@kathy-snider Didn't we think of a solution for this and just never implemented it?

**Comment by ericfeczko** [comment]
That would be fantastic if we could implement! I would use the ABCD defaults if it makes it easier -- this allows collaborators already leveraging ABCD protocols to use the pipeline to go fully to BIDS derivatives. I recently found out that this is a chief complaint for some collaborators, so perhaps low effort for huge benefit.

**Comment by kathy-snider** [comment]
Somehow I didn't get the whole conversation. You just want filemapper to be another stage, right? Like custom-clean, it would run if we gave it a .json file? We can do that.

It's just one of many things I would like to do, but I spend all of my time processing BCP!!! I'll put it on my Trello, but don't hold your breath.


________________________________

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
