### ISSUE TITLE
Pipeline tries to apply DWI fieldmaps to functional runs

### ISSUE THREAD

**Issue by traceyshi** [DCAN-Labs/abcd-hcp-pipeline#30]
Pipeline by default tries to apply DWI fieldmaps to functional data, causing FMRIVolume to throw dimension mismatch errors. I tried adding intendedfor sidecars to the .json for the functional fieldmaps, but this didn’t fix the problem.

For reference, deleting/moving the DWI fieldmaps from the rawdata/fmap directory seems to avoid this error (but ideally would be great to not have to do this).

This issue was identified using HBN data from public release 7.

**Comment by ericearl** [comment]
@perronea I think we should make the "intended for" collection be the only thing that lets field maps get selected.  And warn the user if they are processing functional data without a field map.  What do you think?

**Comment by arueter1** [comment]
The next version of the pipeline that will be released will have this issue resolved.
