### ISSUE TITLE
multiple sessions 

### ISSUE THREAD

**Issue by juansanchezpena** [DCAN-Labs/abcd-hcp-pipeline#31]
I am trying to pre-process a single subject with two sessions. The first session has anat, func and fmaps, the second has func and fmaps. The fmaps and func at ses-1 and ses-2 are the exact same series. I have been unable to run the abcd-hcp preprocessing pipelines on both sessions. I think it has to do with the syntax of the func names but am unsure. I tried -all-sessions and it did not work either. Does anyone have any experience in this issue?
Thanks

**Comment by arueter1** [comment]
Hi There! Could we get some more information from you? Could you give us the error you got in the pipeline (without giving any subIDs)? One thing that can happen is having multiple run1 (e.g. run1_pa and run1_ap) will need to be renamed to be consecutive.

**Comment by perronea** [comment]
@juansanchezpena The pipeline does not automatically use the anats from one session for another session if they do not exist for that other session. This is a unique use case that is not usually recommended. You will need to copy the anat from ses-1 to an anat directory in ses-2 and process them separately.

**Comment by juansanchezpena** [comment]
Thank you Anders

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
