### ISSUE TITLE
freesurfer output

### ISSUE THREAD

**Issue by mriedel56** [DCAN-Labs/abcd-hcp-pipeline#33]
Is it possible to make the direct freesurfer output available for the ABCD data? Ive checked out the filemapper and it looks like those files are just skipped over (presumably bc they are intermediary for final output files). Is space an issue for that?

**Comment by arueter1** [comment]
Thanks for the question! Someone from our team will check in on this as soon as we are able.

**Comment by ericfeczko** [comment]
Hi mriedel56!
Unfortunately, the output from the intermediate Freesurfer stage (see here for further information: https://collection3165.readthedocs.io/en/stable/pipeline/#stage-2-freesurfer ) remains quite large (~ 612 MB per subject, ~6 TB total ~ approximately 10 percent of the size of current derivatives), and is not available right now. 

However, the anat derivative folder contains the midthickness surfaces for both MNI and native spaces, surface-based morphometrics stored as CIFTIs, the volume in MNI space, and the correspond anatomical segmentation. Depending on what you are interested in doing, we may be able to help you answer your question using the derivatives that are already available ( https://collection3165.readthedocs.io/en/stable/derivatives/).

Please let us know how we can help further, thanks!

-Eric

**Comment by mriedel56** [comment]
Thanks for the response, I figured that space had something to do with it. We were potentially interested in running fMRIPREP on the BIDS dataset (just what we use and are more familiar with in our lab). Having freesurfer previously run would have expedited the process, but I think fMRIPREP prefers a newer version of freesurfer. As it stands, the hcp derivatives work perfectly fine for our needs. Thanks again.
