### ISSUE TITLE
Time-series ready for correlation?

### ISSUE THREAD

**Issue by mriedel56** [DCAN-Labs/abcd-hcp-pipeline#34]
We are interested in calculating a dense connectome similar to the HCP. I know those files are quite large, so I imagine thats why they were not shared, but I was wondering if I can calculate it directly from the following file type:
sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_bold_desc-filtered_timeseries.dtseries.nii

That is, have these been sufficiently processed to the point that they are ready for correlation? Do I need to incorporate motion censoring using the associated files? I dont recall the HCP stance on that.

**Comment by arueter1** [comment]
Thanks for reaching out! We will get back to you about this question soon.

**Comment by mriedel56** [comment]
Thanks for the information. Any recommendation on algorithm for signal outlier detection? I think the only one Im familiar with is based in AFNI, and I dont know if it will work on vertex data. 

Thanks for the references to calculate dense connectomes! I'll check those out, maybe it will resolve my question above.
