### ISSUE TITLE
Files not available for download

### ISSUE THREAD

**Issue by mriedel56** [DCAN-Labs/abcd-hcp-pipeline#35]
Sorry if this is the wrong place for this comment. We are downloading files from Collection 3165 - DCAN Labs ABCD-BIDS, and we have alot of instances of files that do not download (for example, event timing files, or ABCD-HCP processed MNI bold images); we also have alot of participants that completely download as expected. I dont think its an issue with the downloader, and I imagine the participants made available in the collection passed the expected output stage. Maybe some links in the manifest are incorrect? I have a text file for each file type with the failed subjects if it would help give some examples of the problem.

**Comment by arueter1** [comment]
Thanks for reaching out! We will get back to you about this soon.

**Comment by mriedel56** [comment]
Thanks for the response! I created a sort of "pseudo-manifest" that contains the missing information/links based on examples in the original. For example, if one participant was missing the *space-MNI_bold.nii.gz derivative, but had the motion.tsv files, I would recreate a line in the manifest using the same dataset ID/collection/manifest/etc. with the appropriate S3 link, but it returned an error as if the file does not exist on the S3 server. Happy to continue working on this off thread. miriedel@fiu.edu.

**Comment by perronea** [comment]
@mriedel56 it looks like that data is indeed missing. We've had some issues with the NDA upload process that we are currently working on resolving with them. Thank you for bringing this to our attention. I'm going to close the issue here and open a new one on the nda-abcd-s3-downloader (https://github.com/DCAN-Labs/nda-abcd-s3-downloader/issues/24)
