### ISSUE TITLE
Singularity image

### ISSUE THREAD

**Issue by manalilatkar** [DCAN-Labs/abcd-hcp-pipeline#4]
Hello,
In the README, you mention that you can send a singularity image if asked. We need the singularity recipe for a client at [ICS Penn State](https://ics.psu.edu). Would it be possible for you to help us with that?
Thank you.

**Comment by dasturge** [comment]
Hello, we are currently tidying up the README.md, the changes can be found in this commit: 5d3fa0a

If you already have Singularity installed, one of these options should work for you to acquire the image from the online repository:
```
singularity pull docker://dcanlabs/abcd-hcp-pipline

singularity build abcd-hcp-pipeline.img docker://dcanlabs/abcd-hcp-pipeline
```

Let me know if this solves your issue.

**Comment by dasturge** [comment]
documentation on the singularity build is now included.
