### ISSUE TITLE
DCAN BOLD Processing Derivatives for Seed-Based Analysis

### ISSUE THREAD

**Issue by fmriuser** [DCAN-Labs/abcd-hcp-pipeline#41]
Hello,

I have preprocessed pediatric resting state data using the DCAN pipeline. I am looking to take the BOLD functional image for each subject and upload them into CONN toolbox to conduct a seed-based analysis. 

My questions are: 
1. Which derivative of the DCAN preprocessing is the BOLD functional file for each subject? 
2. Would you recommend any other processing steps before first-level processing (i.e. smoothing, denoising/band-pass filtering, etc.) within CONN Toolbox? 

Thank you very much!
Mariam

**Comment by ericfeczko** [comment]
Hi Mariam!

My sincerest apologies for the late response! 

1) The `sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_run-#_space-MNI_bold.nii.gz` files in the `func` derivatives directory are motion-corrected and minimally pre-processed volumes registered to the MNI space (registration is done via a single resampling). 

2) They have not undergone any connectivity pre-processing nor spatial smoothing, so I would recommend performing denoising/band-pass filtering, and quality control using the motion data from `sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_run-#_desc-filtered_motion.tsv`. We also have a version containing a column for the framewise-displacement (FD) as well: `sub-#/ses-#/func/sub-#_ses-#_task-(MID|nback|SST|rest)_run-#_desc-filteredincludingFD_motion.tsv`. 

You can find more information about the derivatives at our regularly updated readthedocs page, here :)

https://collection3165.readthedocs.io/en/stable/derivatives/

**Comment by fmriuser** [comment]
Hello, 

Thank you so much for your detailed response!

I am having trouble locating the files. This is how my directory looks, and I do not see a file with the same labels. Do you happen to have any insight as to why this might be? 

<img width="912" alt="Screen Shot 2021-09-27 at 9 27 45 AM" src="https://user-images.githubusercontent.com/81822227/134917790-dd48e99f-3e47-4782-b299-514c2fd782b9.png">

<img width="915" alt="Screen Shot 2021-09-27 at 9 29 14 AM" src="https://user-images.githubusercontent.com/81822227/134918060-87049c15-3dce-4ece-aa24-b7017724fd43.png">

Thank you very much!

**Comment by ericfeczko** [comment]
My apologies, I completely misunderstood the question -- I realize now you're asking about the pipelines outputs directly (thanks for the example!).

The output of the docker image is, unfortunately, not in a BIDS derivative format*. In that current format, it depends on how you want to do the analysis. The *final* output is actually under MNINonLinear/Results. In that folder there is an atlas dtseries file that is in a CIFTI format (dtseries.nii). Using workbench command -cifti-separate ( see here: `https://www.humanconnectome.org/software/workbench-command/-cifti-smoothing`), you can split the CIFTI file into GIFTIs and a volumetric file. The volumetric file will only contain subcortical data, however.

The MNINonLinear/Results/task-rest??/ folders contain the functional data resampled to the atlas space. Unfortunately, our denoising only occurs on the CIFTIs themselves, so if you use the volumes inside, you'll want to run denoising on them. You may also want to use the motion analysis found in `DCANBOLDProc_4.0.0/motion/FD_power_2014_only.mat` file, which contains a list of temporal masks to account for the motion artifact. Our denoising procedure accounts for the filtering frequency artifact found in motion data, while interpolating for excessively bad frames (FD > 0.3). 


If you're interested, we do have a seed map analyses stream for our CIFTIs, you are certainly welcome to use that if you'd like. I need to check with our team to make sure its available for use. I should be able to post back this afternoon. 


*You can use filemapper to do so, if you want a smaller footprint for your dataset: `https://github.com/DCAN-Labs/file-mapper/`. The `https://github.com/DCAN-Labs/file-mapper/blob/master/examples/abcd-filemapper.json` will produce ABCC style derivatives for you from the pipeline.


 Hope this helps! I'll reopen the issue until this is fully addressed

**Comment by fmriuser** [comment]
Hello, 

Thank you for all the information. Having a seed map analyses stream for the CIFTIs would be great. If that is available for use, I would very much appreciate it!

Best,
Mariam

**Comment by fmriuser** [comment]
Hello, 

I was wondering if there is an update on the availability of this seed map analysis pipeline? 

Also, I would like some clarification as to which specific file outputs from the filemapper I would be able to pull into CONN for smoothing/band pass filtering and denoising. 

Is that this file?
<img width="1140" alt="Screen Shot 2021-10-05 at 10 51 04 AM" src="https://user-images.githubusercontent.com/81822227/136047155-60328bb6-52ae-4b6a-a924-74001517958f.png">
 
Or, is it MNI_NonLinear/Results/**_"one of the files listed below"_**

<img width="1195" alt="Screen Shot 2021-10-05 at 10 49 51 AM" src="https://user-images.githubusercontent.com/81822227/136046921-f270cc09-8720-409d-b93b-9dfd7e7139b2.png">

Thank you very much for your time, 
Mariam

**Comment by ericfeczko** [comment]
Hi Mariam,

My apologies for the very late reply 

1.  The seed map code is available privately, but I was hoping we could have it moved to public. If you can email me at feczk001@umn.edu I can provide access and some documentation.

2. T1 and motion regressor are perfect, You'll want to grab the file task-rest01.nii.gz file from MNINonLinear/Results/task-rest01 subfolder as well -- hope this helps!
