### ISSUE TITLE
Fails for anat only data when --ignore func flag isn't specified

### ISSUE THREAD

**Issue by audreymhoughton** [DCAN-Labs/abcd-hcp-pipeline#43]
If you have data that contains some subjects with functional data and some without, you cannot submit one run command for the pipeline. You have submit one command for the subjects with functional data and one for the subjects without that includes the `--ignore func` flag. 

If the pipeline could check what is in the subject directory and default to` --ignore func` for subjects without functional data, that would be ideal.

**Comment by LuciMoore** [comment]
@audreymhoughton is this still a problem?

**Comment by audreymhoughton** [comment]
@LuciMoore it was never fixed to my knowledge

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
