### ISSUE TITLE
FreeSurfer version

### ISSUE THREAD

**Issue by dpagliaccio** [DCAN-Labs/abcd-hcp-pipeline#45]
Is it possible to run the abcd-hcp-pipeline using the newest version of FreeSurfer?

**Comment by arueter1** [comment]
Hi David,

Great question! At this point in time the abcd-hcp-pipeline does not run with the newest version of FreeSurfer. In the next few months there will be a 2nd version that is incorporated with fmriprep that will be able to use the newest version of FreeSurfer. I would suggest "watching" this repo to ensure that you are alerted to any new versions. If you have any further questions, please do not hesitate to reach out.

Thanks!
Amanda
