### ISSUE TITLE
Exact Container Call and Version for ABCC BIDS Derivatives

### ISSUE THREAD

**Issue by tjhendrickson** [DCAN-Labs/abcd-hcp-pipeline#46]
I'm sorry I know I asked this a while ago, but I think I forgot to save it. What was the exact call and container version for the abcd-hcp-pipeline when processing the ABCC BIDS derivatives? A colleague is looking to replicate results. 

Additionally, if you have the configuration file used for DCANBoldPreProc that would be helpful!

**Comment by ericfeczko** [comment]
Sorry, I forgot to answer this until now!

0.03 for the docker container and 2.0.0 for the code base itself. 

I can't put an exact usage, since I don't remember the bandstop we used. @perronea can you provide an example with the correct band stop filter numbers? Thanks!

**Comment by tjhendrickson** [comment]
Here is an example usage with docker as it was run to generate ABCC outputs.

sudo /opt/acc/sbin/exadocker run --name=`basename ${TempSubjectDir}` --rm -v ${TempSubjectDir}/BIDS_unprocessed:/bids_input:ro -v ${TempSubjectDir}/BIDS_processed:/output -v ${TempSubjectDir}/cleaning.json:/cleaning.json -v ${TempSubjectDir}/license.txt:/opt/freesurfer/license.txt dcanlabs/abcd-hcp-pipeline:dev /bids_input /output --freesurfer-license=/opt/freesurfer/license.txt --participant-label=${participant} --ncpus=${CPU_CORES} --bandstop 18.582 25.7263 --custom-clean /cleaning.json
