### ISSUE TITLE
How should multiple sessions be handled?

### ISSUE THREAD

**Issue by iamdamion** [DCAN-Labs/abcd-hcp-pipeline#47]
Question: I have been testing the pipeline using a single subject and single session. However, our collections are longitudinal and we preprocess as scans come in. I see that there's an argument to process all sessions for a subject as one. However, the help doesn't show an argument to specify a single session and it's unclear how multiple sessions are handled if they are slowly being added.

If one session is processed and then a new session is BIDS sorted and added, if the pipeline is run again for that subject, will it check for outputs, skip the already processed session, and only process the new session? Or will it try to reprocess all ses- folders under that sub- folder?

If the latter, how do you suggest we handle our workflow using the DCAN pipeline (processing only a single session)? Thanks.

**Comment by arueter1** [comment]
Hi Damion! Thanks for the question. I've assigned @ericfeczko and @hough129 to this and they will get back to you as soon as they are able. Please note that we are experience a very high volume of collaborator requests at this point in time, so we are experiencing some delays in getting back to folks. Thanks in advance for your patience!

**Comment by madisoth** [comment]
Hi Damion,

I am not set up to test this right now, but I believe --participant-label can actually accept either:

(1) a list of subject IDs, or
(2) a Python dictionary with subject IDs as the keys, and session ID lists as the values

In case (1) I believe all sessions for the subject(s) would be reprocessed. In (2) only the specified subject-session pair(s) should be processed. 

I am in total agreement that should be made explicit in the documentation (assuming it actually works as I am guessing), or we just should make it two separate options, --participant-label and --session-id, to be consistent with nhp-abcd-bids-pipeline and infant-abcd-bids-pipeline.    

--participant-label

**Comment by iamdamion** [comment]
@madisoth Looks like @ericearl and I are going to take a stab at this on friday. We'll update here if we get a PR ready.

**Comment by arueter1** [comment]
I believe the pull request went through. I am going to close this out. Feel free to open it again if necessary!
