### ISSUE TITLE
Query - enback eprime files

### ISSUE THREAD

**Issue by richardbeare** [DCAN-Labs/abcd-hcp-pipeline#51]
Hi,
I'm returning to abcd-hcp-pipeline after a long break, so I'm probably out of date. I have new data acquired using protocols derived from ABCD. The emotional nback used, as far as I know, the eprime implementation used in the ABCD study conducted at the same site. Are there established procedures for importing eprime to bids and processing with the pipeline?

Thanks

**Comment by arueter1** [comment]
Hi @richardbeare - apologies for the long delay, our lab is slammed right now. I am asking @ericfeczko if he has any insights into this. We will get back to you as soon as we are able. Thanks for your patience!
