### ISSUE TITLE
version 0.1.0 question

### ISSUE THREAD

**Issue by juansanchezpena** [DCAN-Labs/abcd-hcp-pipeline#56]
Dear ABCD developers,
I am testing the newest version of abcd using the session flag. Two questions:
1. If there are two sessions is the first one processed before the second by default?
2. Is there anywhere in the logs or the summary that confirms pipeline version?
Juan

**Comment by ericearl** [comment]
@juansanchezpena I'll try to answer that, but no guarantees I'm 100% right here...

1. I think so, but not sure.  Does it matter as long as they are processed?  They should be processed independently, not reliant on each other for data or processing.
2. Your `docker run` call should use the docker "tag" of the version you want.  Using no docker tag will always give you the `latest`, which may change versions occasionally as features are developed and bugs are fixed.

**Comment by juansanchezpena** [comment]
Thanks Eric
I was curious if the version was found somewhere specifically in the output files (i.e. executive summary etc) but I haven’t been able to find it
J

From: Eric Earl ***@***.***>
Date: Monday, January 3, 2022 at 12:21 PM
To: DCAN-Labs/abcd-hcp-pipeline ***@***.***>
Cc: Sanchez, Juan (NYSPI) ***@***.***>, Mention ***@***.***>
Subject: Re: [DCAN-Labs/abcd-hcp-pipeline] version 0.1.0 question (Issue #56)

ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.


@juansanchezpena<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjuansanchezpena&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7C90c7a16b7e924f8489be08d9cedd7510%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637768272822816914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=U0c%2Blan36k%2F9CrtMFscZFrY%2Ft2jh2DodRcefRSLNJ1k%3D&reserved=0> I'll try to answer that, but no guarantees I'm 100% right here...

  1.  I think so, but not sure. Does it matter as long as they are processed? They should be processed independently, not reliant on each other for data or processing.
  2.  Your docker run call should use the docker "tag" of the version you want. Using no docker tag will always give you the latest, which may change versions occasionally as features are developed and bugs are fixed.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDCAN-Labs%2Fabcd-hcp-pipeline%2Fissues%2F56%23issuecomment-1004238682&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7C90c7a16b7e924f8489be08d9cedd7510%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637768272822816914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q0BBG5OWOh3gw8sAeC1DWPxM2%2F2l0E8Tq5RC4YzcE2Q%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARKALFCTQN6D2T6KT55W5S3UUHLI7ANCNFSM5K2ZMTLQ&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7C90c7a16b7e924f8489be08d9cedd7510%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637768272822816914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2F5LPdvgjicVr9PiRagKLrZyKBahn98uDQJZKNCo7JmM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7C90c7a16b7e924f8489be08d9cedd7510%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637768272822816914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7u4H83W6Sj5F2i9WLsYHn%2BMMW8I0W9OnEXG1evnlv6g%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CJuan.Sanchez%40nyspi.columbia.edu%7C90c7a16b7e924f8489be08d9cedd7510%7Cf46cb8ea79004d108ceb80e8c1c81ee7%7C0%7C0%7C637768272822816914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eXXsmzJFAYzbVXvLeG7zIio8R7ychuc8Kb7%2Bx6fYu%2Fc%3D&reserved=0>.

**Comment by madisoth** [comment]
As of v0.1.3, the version string is printed to stdout at each pipeline stage.
