### ISSUE TITLE
[3165] - DCAN Labs ABCD-BIDS Community Collection (ABCC) File Availability

### ISSUE THREAD

**Issue by fmriuser** [DCAN-Labs/abcd-hcp-pipeline#62]
Hello, 

I am looking to download DCAN-processed data from the NDA repository. I was wondering if these files are available for the individual subjects for download: 

**T1:** sub/ses/files/MNINonLinear/T1w_restore_brain
**BOLD Image**: sub/ses/files/task-rest01/task-rest01_nonlin_norm.nii
**Motion Regressor**: sub/ses/files/MNINonLinear/Results/task-rest01/Movement_Regressors.txt
**Another File:** MNINonLinear/Results/task-rest01/task-rest01.nii.gz

Thank you very much!

**Comment by ericearl** [comment]
@fmriuser I just saw this with no answer.  You should try putting this question to:

https://github.com/ABCD-STUDY/nda-abcd-collection-3165/issues

Aside from that, I think what you're looking for is:

https://github.com/DCAN-Labs/nda-abcd-s3-downloader
