### ISSUE TITLE
Clarify run.py input arguments help messages

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-hcp-pipeline#66]
Changes suggested to `app/run.py` during 2022-01-26 code review:

  - Line 28. Update version to 0.1.0
  - Line 89. Change the phrase "the link in the description" to the actual link https://bids.neuroimaging.io/
  - Lines 103-112. Clarify that subject and session IDs are space-separated
  - Lines 167-173. Be more specific about where the bandstop is applied in the DCANBoldProc pipeline
  - Line 175. Rename 'Special pipeline options'?

**Comment by audreymhoughton** [comment]
- version is 0.1.4 now

**Comment by LuciMoore** [comment]
updated
