### ISSUE TITLE
Remove outdated intended run.py functionality

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-hcp-pipeline#67]
Changes suggested to `app/run.py` during 2022-01-26 code review:

  - Lines 187-193. `--abcd-task` should either be deprecated or updated to match the new task pipeline
  - Lines 291-295. Remove `run_dwi` from `interface` function
    - Also, remove the line that crashes if there's dwi and no fmaps

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
