### ISSUE TITLE
Remove redundant and unneeded code from helpers.py (and a few other minor updates)

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-hcp-pipeline#68]
Changes suggested to `app/helpers.py` during recent code reviews:

## Remove redundant and unneeded code (2022-01-26)

  - Lines 96-109 are redundant and can be reduced by half
  - Line 154-155. Delete everything from the `supported_fmaps` list except `epi`
  - Lines 192-253. Remove (and simplify) all of this

### `get_realdwelltime` function

  - Lines 291-293. Add `logger.info` line saying "Calculating real dwell time from these fields [PixelBandwidth, AcquisitionMatrixPE, and ParallelReductionFactorInPlane] instead" to explain if the pipeline crashes due to lacking those fields

### `ijk_to_xyz` function

  - Lines 380-389. Change how 'dwi' is handled to how 'func' is handled?
    - Or at least make sure that it is handled consistently throughout the code

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
