### ISSUE TITLE
Minor fixes to clean up pipelines.py

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-hcp-pipeline#69]
Changes suggested to `app/pipelines.py` during 2022-02-02 code review:

## Replace/modularize redundant code listing arguments

  - Some redundant code used by many of the classes could be replaced with a common function or something because (especially the 'spec' variable) in many of the classes reuses a lot of the same arguments
    - Specifically these functions: PreFreeSurfer (lines 684-694), FreeSurfer(lines 684-694), PostFreeSurfer (lines 712-740), FMRIVolume (lines 750-774), FMRISurface (lines 838-849), and DCANBoldProcessing (lines 872-891) 

### ParameterSettings class

  - Line 19. Finish this unfinished sentence
  - Lines 25-28. 1mm is mislabeled as 0.7mm here, so fix the labeling
  - Lines 52-75. Cite that these magic numbers came from the original HCP pipeline
  - Lines 76-92. Cite that these magic numbers came from DCANBoldProc defaults
  - Lines 118-174. Clean up this block
  - Lines 179-184. "These are straight-up lies," per Audrey H, and "false promises," so they should be deleted
  - Lines 197-199. Delete this block that was commented-out around 2018

### PreFreeSurfer class

  - Line 665. "else" is not aligned with the "if" it refers to on line 662

### DiffusionPreprocessing class

  - Lines 954-971. Remove all of these lines because they were never implemented.
    - That was planned 3 years ago and never implemented

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
