### ISSUE TITLE
Remove planned-but-never-implemented pipelines.py functionality

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-hcp-pipeline#71]
Changes suggested to `app/pipelines.py` during 2022-02-02 code review:

### Stage class

  - Lines 476-485. `get_conditional_expected_outputs` function isn't implemented; we should probably either implement it, remove it, or explain when it will likely be implemented
  - Lines 536-51. Should these functions (which just raise [`NotImplementedError`](https://docs.python.org/3/library/exceptions.html#NotImplementedError)) be removed because we are not planning to continue development of this pipeline, or kept to prevent someone from trying to use non-overridden versions of these functions from this an abstract class? 

### DiffusionPreprocessing class

  - Lines 954-971. Remove all of these lines because they were never implemented
    - That was planned 3 years ago and never implemented

### PreFreeSurfer class

  - Lines 666-670. Remove this block, because often the pipeline shouldn't grab the alphabetically first field map and stick it onto the T1w unless explicitly requested in the .JSON

**Comment by LuciMoore** [comment]
closing enhancement as not planned as we move towards using fMRIPrep
