### ISSUE TITLE
Request for task-residualized data

### ISSUE THREAD

**Issue by mackenziemitchell** [DCAN-Labs/abcd-hcp-pipeline#80]
Hello, 
We have been working with @ericfeczko to use Collection 3165 task fMRI data for functional connectivity. He let us know that task-residualized timeseries have been generated for the baseline year, but not processed through DCAN Bold Proc yet. I am posting here at Eric's suggestion to register a formal request for the processed task-residualized data.
Thank you!
Mackenzie

**Comment by hough129** [comment]
@mackenziemitchell 
Hi Mackenzie,
When is this data needed by?
Thanks,

**Comment by mackenziemitchell** [comment]
@hough129
Hi Audrey,
Mid/late January would be ideal, if possible. Eric made it seem like this was in process, but didn't give a clear estimation of when it could be completed.
Thanks!
Mackenzie

**Comment by hough129** [comment]
Hi @mackenziemitchell - this hasn't been tackled yet to my knowledge. I need to follow-up with my team and get back to you.

**Comment by audreymhoughton** [comment]
Hi @mackenziemitchell - if this data is not present in the C3165, we have it at MSI. Please reach out to me via email (hough129@umn.edu). Apologies for the delay here!
