### ISSUE TITLE
t1 json - missing PixelBandwidth?

### ISSUE THREAD

**Issue by sarahechang123** [DCAN-Labs/abcd-hcp-pipeline#83]
Hi all,

I'm using the following docker call to run the pipeline on ABCD baseline data (just a 5 subject subset to test the pipeline out), but receiving an error:

**Docker call:** docker run --rm -v C:\Users\beardenlab\Desktop\Research\data_abcd_minimallyPreproc\image_files:/bids_input:ro -v C:\Users\beardenlab\Desktop\Research\data_abcd_minimallyPreproc\output:/output -v C:\Users\beardenlab\Desktop\Research\freesurfer\license\license.txt dcanumn/abcd-hcp-pipeline /bids_input /output --freesurfer-license=/opt/freesurfer/license.txt --stage PreFreeSurfer

**Error:** 
Traceback (most recent call last):
  File "/app/run.py", line 397, in <module>
    _cli()
  File "/app/run.py", line 69, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 292, in interface
    session_spec = ParameterSettings(session, out_dir)
  File "/app/pipelines.py", line 106, in __init__
    self.bids_data['t1w_metadata'])
  File "/app/helpers.py", line 295, in get_realdwelltime
    pBW = metadata['PixelBandwidth']
KeyError: 'PixelBandwidth' 

The T1 json has the following fields: RepetitionTime, EchoTime, FlipAngle, InversionTime. None of the subjects that I downloaded have the PixelBandwidth field included in the T1 json. I'm not exactly sure if the missing PixelBandwidth is the issue, or what's going on (new to BIDS specifications) - 

Thanks for your help!

**Comment by hough129** [comment]
Hi @sarahechang123 - the pipeline expects 'PixelBandwidth' in the sidecar JSONs. Missing PixelBandwidth is the issue as you expected! I've previously had to reach out to the people who've acquired the data I'm processing to get that information.

**Comment by hough129** [comment]
@sarahechang123 - I am closing this issue. Please re-open it if you're still experiencing problems!
