### ISSUE TITLE
padding fix for bandpass filtering in DCAN BOLD of dcanumn/abcd-hcp-pipeline not working correctly

### ISSUE THREAD

**Issue by xhaoNY** [DCAN-Labs/abcd-hcp-pipeline#85]
We tested the latest dcanumn/abcd-hcp-pipeline and found the band pass filtering results were not as expected. We further checked the precompiled code inside the docker image and found that "dcan-signal-processing" had the exact same file size as the one inside an old docker image of the same pipeline 10 months ago (15,460,752 bytes). Could it possible that a wrong version of the file was put in the new docker image?

**Comment by madisoth** [comment]
This should be resolved in the current v0.1.3-- we briefly pushed a "broken" v0.1.3 release (including to Dockerhub) without the intended update to dcan_bold_processing.

One way to verify a container is the "fixed" v0.1.3: check the MCRROOT path that's exported in /app/SetupEnv.sh; this line should be present:

`export MCRROOT=/opt/mcr/v91`
