### ISSUE TITLE
segmentation error 

### ISSUE THREAD

**Issue by juansanchezpena** [DCAN-Labs/abcd-hcp-pipeline#88]
Using 0.1.2 container.
 We saw a segmentation error on the Myelin Mapss and cortical thickness. 
![Screen Shot 2023-02-13 at 2 16 07 PM](https://user-images.githubusercontent.com/72615316/218552682-0c555fb9-9fec-449a-ba49-b36947187853.png)
![Screen Shot 2023-02-13 at 2 16 52 PM](https://user-images.githubusercontent.com/72615316/218552815-b4c5ee19-cf47-457d-8a93-b7de1f7ad402.png)

I re ran and the artifact persisted. Could you recommend the best way to fix the error (using freesurfer) and how to plug back into pipeline  or if you can recommend another solution.

**Comment by ericfeczko** [comment]
Its probably a segmentation error with the aseg -- haven't seen it in awhile -- revising the aseg and the plugging it back into the pipeline would work, but the pipeline stages don't divide the segmentation from the initial surface generation (e.g. autorecon-cp). Its possible that the hires refinement would eliminate the issue -- but I'm unsure -- you'd need to rerun the PostFreesurfer stage after fixing the aseg.

**Comment by perronea** [comment]
Side note: There is an unrelated bug in version 0.1.2 that has been fixed in v0.1.3. I just pushed this new version earlier today and I would recommend re-running all your subjects through the last couple stages of this new release with `--stage "DCANBOLDProcessing,ExecutiveSummary"`

**Comment by hough129** [comment]
@juansanchezpena did @ericfeczko 's suggestion above solve your problem? Let us know if you need more information!

**Comment by LuciMoore** [comment]
@juansanchezpena I'm closing this for now due to inactivity. I agree that this is likely just due to an error in the segmentation (perhaps due to raw data quality issues or needing to use more sophisticated segmentation generation techniques like what we've been developing with [BIBSNet](https://github.com/DCAN-Labs/BIBSnet). please reopen if you still need assistance!

**Comment by juansanchezpena** [comment]
No problem thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
