### ISSUE TITLE
Respiration filter recommendations for TR greater than 1?

### ISSUE THREAD

**Issue by iamdamion** [DCAN-Labs/abcd-hcp-pipeline#89]
We have a few datasets we are working with that have a TR above 1 second. This gives us an error using the respiration filter . We saw in the readme that the upper limit of the bandstop argument can't "exceed the Nyquist folding frequency in bpm", which it does with these longer TRs. 

Do you have a suggestion of best practice here? Should we use the script default and turn the filter off completely or would adjusting the range make more sense? Our limit is 17.035 with the TR I'm looking at, so that is above the DCAN pipeline suggested lower limit and I'm hesitant to completely shift that range. Any insight would be appreciated.

**Comment by ericfeczko** [comment]
This should be fixed in either an upcoming release or in the latest version.

**Comment by iamdamion** [comment]
I'll compare which release we are using. Do you know if the fix was turning it off if the value exceeds that limit or was there something done to allow for longer TRs to still use the filtering?

**Comment by madisoth** [comment]
The fix is included in the current version (0.1.3 at this time); the key change was to ensure the filter bandwidth passed to Matlab iirnotch is positive (see commit: https://github.com/DCAN-Labs/dcan_bold_processing/commit/b19024c3276e5a9e8da6f3d41d99a5f0705b78b4)
