### ISSUE TITLE
StudyTemplate fails at PostFreeSurfer

### ISSUE THREAD

**Issue by jarodroland** [DCAN-Labs/abcd-hcp-pipeline#97]
### What happened?

StudyTemplate and StudyTemplateBrain are not passed to PostFreeSurferPipeline.sh: https://github.com/DCAN-Labs/abcd-hcp-pipeline/blob/13d93a3ccd39d699844622ce6be1a65119221cd4/app/pipelines.py#L743C26-L743C26
Fails without error message when AtlasRegistrationToMNI152_ANTsIntermediateTemplate.sh tries to parse the StudyTemplate parameters: https://github.com/DCAN-Labs/DCAN-HCP/blob/92913242419d492aee733a45d454ea319fbaac35/PostFreeSurfer/scripts/AtlasRegistrationToMNI152_ANTsIntermediateTemplate.sh#L114C36-L114C36

### What command did you use?

```shell
docker with --study_template parameter and a custom age relevant template.
```

### What version of the abcd-hcp pipeline are you using?

v0.1.3

### Add any additional information or context about the problem here.

Resolved by editing app/pipelines.py below at https://github.com/DCAN-Labs/abcd-hcp-pipeline/blob/13d93a3ccd39d699844622ce6be1a65119221cd4/app/pipelines.py#L743
...
743:           ' --useStudyTemplate={usestudytemplate}' \\
+++:           ' --studytemplate={studytemplate}' \\
+++:           ' --studytemplatebrain={studytemplatebrain}' \\
744:           ' --printcom={printcom}'
...

**Comment by LuciMoore** [comment]
Hi, @jarodroland. I've updated the code under the branch [postFSstudytemplate](https://github.com/DCAN-Labs/abcd-hcp-pipeline/tree/postFSstudytemplate). We'll try to test this branch to be thorough within the next month, but if you get to it before us and it works please let us know!

**Comment by madisoth** [comment]
v0.1.4 is now out, which has the fixes from the postFSstudytemplate branch -- we believe it should resolve this issue, but if you still run into problems let us know. Thanks!
